//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracking.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSUtilityDBEntities : DbContext
    {
        public MSUtilityDBEntities()
            : base("name=MSUtilityDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TTDates> TTDates { get; set; }
        public virtual DbSet<TTEntryData> TTEntryData { get; set; }
        public virtual DbSet<TTKunde> TTKunde { get; set; }
        public virtual DbSet<TTKundeEntry> TTKundeEntry { get; set; }
        public virtual DbSet<TTProject> TTProject { get; set; }
        public virtual DbSet<TTProjectEntry> TTProjectEntry { get; set; }
    }
}
