//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracking.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTKundeEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTKundeEntry()
        {
            this.TTProjectEntry = new HashSet<TTProjectEntry>();
        }
    
        public int ID { get; set; }
        public int KundeID { get; set; }
        public int DateID { get; set; }
    
        public virtual TTDates TTDates { get; set; }
        public virtual TTKunde TTKunde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTProjectEntry> TTProjectEntry { get; set; }
    }
}
