//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracking.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTProjectEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTProjectEntry()
        {
            this.TTEntryData = new HashSet<TTEntryData>();
        }
    
        public int Id { get; set; }
        public int KundeEntryId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual TTKundeEntry TTKundeEntry { get; set; }
        public virtual TTProject TTProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTEntryData> TTEntryData { get; set; }
    }
}
